#Requires -Version 5.1
<#
.SYNOPSIS
    Builds the optimizer, launches Windows Sandbox, and waits for the result.

.DESCRIPTION
    The sandbox runs Start-SandboxRun.ps1 on logon, which applies the optimizer
    for real, verifies the changes landed, runs the undo script, and verifies the
    machine is back where it started. Results come back through the writable
    mapped folder because the sandbox itself is destroyed on close.

    Nothing here touches the host: the project is mapped read-only and every
    change happens inside the container.
#>
[CmdletBinding()]
param(
    [int]$TimeoutMinutes = 20,
    [switch]$NoBuild
)

$ErrorActionPreference = 'Stop'
$root    = Split-Path $PSScriptRoot -Parent
$results = Join-Path $PSScriptRoot 'results'

# Presence of the executable is the check that matters and, unlike
# Get-WindowsOptionalFeature, it does not need an elevated session. The feature
# can read as Enabled while the binary is still absent, which is exactly the
# state between enabling it and rebooting.
$sandboxExe = "$env:WinDir\System32\WindowsSandbox.exe"
if (-not (Test-Path $sandboxExe)) {
    Write-Host 'Windows Sandbox is not available yet.' -ForegroundColor Red

    # Get-WindowsOptionalFeature needs elevation, so fall back to the pending-
    # reboot markers, which any user can read. Telling someone to re-enable a
    # feature they already enabled is worse than saying nothing.
    $pending = @(
        'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending',
        'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired'
    ) | Where-Object { Test-Path $_ }

    $renames = $false
    try {
        $renames = $null -ne (Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager' `
                              -Name PendingFileRenameOperations -ErrorAction Stop).PendingFileRenameOperations
    } catch { }

    if ($pending.Count -gt 0 -or $renames) {
        Write-Host '  A restart is pending. The feature is enabled; the binary appears after you reboot.' -ForegroundColor Yellow
        Write-Host '  Reboot, then run this again.' -ForegroundColor Yellow
    } else {
        Write-Host '  No pending restart detected - the feature is probably not enabled.' -ForegroundColor Yellow
        Write-Host '  Run test\Enable-VirtualisationFeatures.ps1 elevated, then reboot.' -ForegroundColor Yellow
    }
    exit 2
}

if (-not $NoBuild) {
    Write-Host 'Building...' -ForegroundColor Cyan
    & (Join-Path $root 'build.ps1') | Select-Object -Last 1
}

# Clear previous results so a stale exitcode cannot be mistaken for this run's.
# Empty the folder rather than removing it. A sandbox still holding the mapped
# folder open makes the directory itself undeletable, and refusing to start
# because a previous container is lingering is a poor reason to fail.
New-Item -ItemType Directory -Force -Path $results | Out-Null
Get-ChildItem -LiteralPath $results -Force -ErrorAction SilentlyContinue |
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
if (Get-ChildItem -LiteralPath $results -Force -ErrorAction SilentlyContinue) {
    Write-Host 'The results folder is still in use - close any open Windows Sandbox first.' -ForegroundColor Red
    exit 2
}

# Written here rather than checked in. A .wsb file cannot expand an environment
# variable or a relative path in <HostFolder>, so a committed one would carry
# whatever absolute path it was authored at and fail to launch for anyone who
# cloned the repo to a different location.
$wsb = Join-Path $PSScriptRoot 'sandbox.wsb'
$wsbXml = @"
<Configuration>
  <!--
    Windows Sandbox test bed for trim. GENERATED by Invoke-SandboxTest.ps1 -
    edit that script, not this file.

    The project is mapped READ-ONLY so a test run cannot corrupt the source.
    Only the results folder is writable, which is how output gets back to the
    host: the sandbox is destroyed on close, and everything else in it with it.
  -->
  <VGpu>Enable</VGpu>
  <Networking>Enable</Networking>
  <MemoryInMB>8192</MemoryInMB>

  <MappedFolders>
    <MappedFolder>
      <HostFolder>$([System.Security.SecurityElement]::Escape($root))</HostFolder>
      <SandboxFolder>C:\opt</SandboxFolder>
      <ReadOnly>true</ReadOnly>
    </MappedFolder>
    <MappedFolder>
      <HostFolder>$([System.Security.SecurityElement]::Escape($results))</HostFolder>
      <SandboxFolder>C:\results</SandboxFolder>
      <ReadOnly>false</ReadOnly>
    </MappedFolder>
  </MappedFolders>

  <LogonCommand>
    <Command>powershell.exe -NoProfile -ExecutionPolicy Bypass -NoExit -File C:\opt\test\Start-SandboxRun.ps1</Command>
  </LogonCommand>
</Configuration>
"@

# The configuration was composed above and never written. Every run launched
# the sandbox against a file that did not exist.
#
# Start-Process on the missing .wsb said "The system cannot find the file
# specified", which was exactly true and was read as a file-association
# problem. Launching WindowsSandbox.exe with the path instead made it worse:
# the executable ignores a configuration it cannot read and starts a default
# sandbox, with no mapped folders and no logon command, which then sits there
# looking busy until the harness times out twenty minutes later.
Set-Content -LiteralPath $wsb -Value $wsbXml -Encoding UTF8

if (-not (Test-Path -LiteralPath $wsb)) {
    Write-Host "Could not write the sandbox configuration to $wsb." -ForegroundColor Red
    exit 1
}

Write-Host "Launching Windows Sandbox ($wsb)..." -ForegroundColor Cyan
Write-Host 'A sandbox window will open and run the test. Leave it alone.' -ForegroundColor DarkGray

# Through the executable rather than the file type: launching a .wsb by
# association depends on Windows Sandbox having been installed in the way that
# registers one, and $sandboxExe was already resolved and checked at the top of
# this script. The silent-default behaviour above is why the file is verified
# first rather than trusted.
Start-Process -FilePath $sandboxExe -ArgumentList "`"$wsb`""

$exitFile = Join-Path $results 'exitcode.txt'
$deadline = (Get-Date).AddMinutes($TimeoutMinutes)
Write-Host "Waiting up to $TimeoutMinutes minutes for a result..." -ForegroundColor DarkGray

while ((Get-Date) -lt $deadline) {
    if (Test-Path $exitFile) {
        # Written empty when the sandbox died before it could report; calling
        # .Trim() on that null is how the harness itself used to crash.
        $raw = Get-Content $exitFile -Raw -ErrorAction SilentlyContinue
        if ([string]::IsNullOrWhiteSpace($raw)) { Start-Sleep -Seconds 2; continue }
        $code = $raw.Trim()
        Write-Host ''
        Write-Host "Sandbox verification exit code: $code" -ForegroundColor $(if ($code -eq '0') { 'Green' } else { 'Red' })
        Write-Host "Full log: $(Get-ChildItem $results -Filter 'sandbox-run_*.log' | Select-Object -First 1 -ExpandProperty FullName)"
        Write-Host ''
        Write-Host 'Close the sandbox window when you are done reading it - everything inside is discarded.' -ForegroundColor DarkGray
        exit [int]$code
    }
    Start-Sleep -Seconds 10
}

Write-Host ''
Write-Host "Timed out after $TimeoutMinutes minutes with no result." -ForegroundColor Red
Write-Host 'Check the sandbox window - it may be waiting on something, or the logon command failed to start.' -ForegroundColor Red
exit 3
