#Requires -Version 5.1
<#
.SYNOPSIS
    Compiles src\*.ps1 into a single distributable trim.ps1.

.DESCRIPTION
    `irm <url> | iex` can only fetch one file, so the modular source has to be
    concatenated into one. This is the same pattern winutil uses.

    Files are concatenated in filename order, so the numeric prefixes are the
    build order: 01-header must come first (it holds the param block, which
    PowerShell requires at the top of a script) and 99-main last.

    There are no external asset dependencies: the NVIDIA profile is composed at
    runtime by Get-NvidiaSettings, per detected card, rather than shipped as a
    file the compiled script would have to find.
#>
[CmdletBinding()]
param(
    # Resolved below, not here: $PSScriptRoot is not reliably populated while a
    # param block's defaults are being evaluated, which makes `powershell -File
    # .uild.ps1` fail on a line that looks perfectly correct.
    [string]$OutFile
)

$ErrorActionPreference = 'Stop'

if (-not $OutFile) { $OutFile = Join-Path $PSScriptRoot 'trim.ps1' }
$srcDir = Join-Path $PSScriptRoot 'src'
$files  = Get-ChildItem -LiteralPath $srcDir -Filter '*.ps1' | Sort-Object Name

if ($files.Count -eq 0) { throw "No source files in $srcDir" }

Write-Host "Compiling $($files.Count) source file(s)..." -ForegroundColor Cyan

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('# ============================================================================')
[void]$sb.AppendLine('#  Trim - COMPILED. Do not edit this file.')
[void]$sb.AppendLine('#  Edit src\*.ps1 and run build.ps1.')
# Provenance, but NOT a wall clock. This project publishes a SHA256 and asks
# people to check it, which is only meaningful if the same sources compile to
# the same bytes - stamping the build time meant two builds of identical source
# never matched, so the fingerprint could only ever be compared against what the
# publisher happened to upload, never reproduced from the repo.
#
# The commit is stable for a given source state, so it identifies the build
# without making it unrepeatable. Outside a git checkout there is nothing
# truthful to say, so it says that.
$commit = 'unversioned source tree'
try {
    $described = & git -C $PSScriptRoot rev-parse --short=12 HEAD 2>$null
    if ($LASTEXITCODE -eq 0 -and $described) {
        $dirty = & git -C $PSScriptRoot status --porcelain 2>$null
        $commit = "commit $described" + $(if ($dirty) { ' (+ uncommitted changes)' } else { '' })
    }
} catch { }
[void]$sb.AppendLine("#  Source: $commit")
[void]$sb.AppendLine('# ============================================================================')
[void]$sb.AppendLine('')

foreach ($f in $files) {
    Write-Host "  + $($f.Name)" -ForegroundColor DarkGray
    [void]$sb.AppendLine("#region $($f.Name)")
    # -Encoding UTF8 is not optional: PowerShell 5.1's Get-Content defaults to
    # ANSI, which silently corrupts any non-ASCII character in the sources.
    # TrimStart on U+FEFF as well: a source file with a byte order mark would
    # otherwise contribute one in the middle of the concatenated output, where
    # it is not a marker at all, just a stray character.
    [void]$sb.AppendLine((Get-Content -Raw -Encoding UTF8 -LiteralPath $f.FullName).TrimStart([char]0xFEFF).TrimEnd())
    [void]$sb.AppendLine("#endregion $($f.Name)")
    [void]$sb.AppendLine('')
}

# 99-main.ps1 ends with Invoke-Main, so the compiled script is self-executing.
# No byte order mark, and a check that none is needed.
#
# `irm ... | iex` is the way almost everyone runs this. Invoke-RestMethod passes
# a leading U+FEFF straight through into the string, and Invoke-Expression
# cannot parse a script that begins with one - it fails on the param block with
# "Unexpected attribute 'CmdletBinding'". A BOM here breaks the product's
# primary install path.
#
# A BOM is only needed to tell a reader the file is UTF-8, and that only matters
# if the file contains characters that differ between UTF-8 and the ANSI code
# page. Pure ASCII decodes identically either way, so the artefact is written
# without one - and the build refuses to continue if anything non-ASCII creeps
# in, rather than silently reintroducing the mark.
$compiled = $sb.ToString()
$nonAscii = @($compiled.ToCharArray() | Where-Object { [int]$_ -gt 127 })
if ($nonAscii.Count) {
    $sample = ($nonAscii | Select-Object -Unique -First 6 | ForEach-Object { 'U+{0:X4}' -f [int]$_ }) -join ', '
    Write-Host "BUILD FAILED - the compiled script contains $($nonAscii.Count) non-ASCII character(s): $sample" -ForegroundColor Red
    Write-Host '  A non-ASCII artefact needs a byte order mark, and a byte order mark breaks irm | iex.' -ForegroundColor Yellow
    exit 1
}

[System.IO.File]::WriteAllText($OutFile, $compiled, (New-Object System.Text.UTF8Encoding $false))

# Parse the result rather than trusting that concatenation produced valid
# PowerShell. A build that emits a syntactically broken script is worse than a
# build that fails.
$errors = $null
[void][System.Management.Automation.Language.Parser]::ParseFile($OutFile, [ref]$null, [ref]$errors)
if ($errors -and $errors.Count -gt 0) {
    Write-Host ''
    Write-Host "BUILD FAILED - $($errors.Count) parse error(s):" -ForegroundColor Red
    foreach ($e in $errors) {
        Write-Host "  line $($e.Extent.StartLineNumber): $($e.Message)" -ForegroundColor Red
    }
    exit 1
}

# Publish the fingerprint beside the artefact. This is what a user compares
# against, and what a release pipeline should attach to the release.
$hash = (Get-FileHash -LiteralPath $OutFile -Algorithm SHA256).Hash
$sidecar = "$OutFile.sha256"
Set-Content -LiteralPath $sidecar -Value "$hash  $(Split-Path $OutFile -Leaf)" -Encoding ASCII

$size = [Math]::Round((Get-Item $OutFile).Length / 1KB, 1)
Write-Host ''
Write-Host "Built $OutFile ($size KB, parses clean)" -ForegroundColor Green
Write-Host "SHA256 $hash" -ForegroundColor DarkGray
Write-Host "       -> $sidecar" -ForegroundColor DarkGray
