#Requires -Version 5.1
<#
.SYNOPSIS
    Compiles src\*.ps1 into a single distributable trim.ps1.

.DESCRIPTION
    `irm <url> | iex` can only fetch one file, so the modular source has to be
    concatenated into one. This is the same pattern winutil uses.

    Files are concatenated in filename order, so the numeric prefixes are the
    build order: 01-header must come first (it holds the param block, which
    PowerShell requires at the top of a script) and 99-main last.

    There are no external asset dependencies: the NVIDIA profile is composed at
    runtime by Get-NvidiaSettings, per detected card, rather than shipped as a
    file the compiled script would have to find.
#>
[CmdletBinding()]
param(
    [string]$OutFile = (Join-Path $PSScriptRoot 'trim.ps1')
)

$ErrorActionPreference = 'Stop'

$srcDir = Join-Path $PSScriptRoot 'src'
$files  = Get-ChildItem -LiteralPath $srcDir -Filter '*.ps1' | Sort-Object Name

if ($files.Count -eq 0) { throw "No source files in $srcDir" }

Write-Host "Compiling $($files.Count) source file(s)..." -ForegroundColor Cyan

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('# ============================================================================')
[void]$sb.AppendLine('#  Trim - COMPILED. Do not edit this file.')
[void]$sb.AppendLine('#  Edit src\*.ps1 and run build.ps1.')
[void]$sb.AppendLine("#  Built: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
[void]$sb.AppendLine('# ============================================================================')
[void]$sb.AppendLine('')

foreach ($f in $files) {
    Write-Host "  + $($f.Name)" -ForegroundColor DarkGray
    [void]$sb.AppendLine("#region $($f.Name)")
    # -Encoding UTF8 is not optional: PowerShell 5.1's Get-Content defaults to
    # ANSI, which silently corrupts any non-ASCII character in the sources.
    [void]$sb.AppendLine((Get-Content -Raw -Encoding UTF8 -LiteralPath $f.FullName).TrimEnd())
    [void]$sb.AppendLine("#endregion $($f.Name)")
    [void]$sb.AppendLine('')
}

# 99-main.ps1 ends with Invoke-Main, so the compiled script is self-executing.
# UTF8Encoding($true) - explicitly WITH a byte order mark. Set-Content -Encoding
# UTF8 means "with BOM" on Windows PowerShell and "without BOM" on PowerShell 7,
# so relying on it made the shipped script's correctness depend on which shell
# happened to run the build. Without a BOM, Windows PowerShell reads this file
# as ANSI and the banner becomes mojibake that will not parse.
[System.IO.File]::WriteAllText($OutFile, $sb.ToString(), (New-Object System.Text.UTF8Encoding $true))

# Parse the result rather than trusting that concatenation produced valid
# PowerShell. A build that emits a syntactically broken script is worse than a
# build that fails.
$errors = $null
[void][System.Management.Automation.Language.Parser]::ParseFile($OutFile, [ref]$null, [ref]$errors)
if ($errors -and $errors.Count -gt 0) {
    Write-Host ''
    Write-Host "BUILD FAILED - $($errors.Count) parse error(s):" -ForegroundColor Red
    foreach ($e in $errors) {
        Write-Host "  line $($e.Extent.StartLineNumber): $($e.Message)" -ForegroundColor Red
    }
    exit 1
}

# Publish the fingerprint beside the artefact. This is what a user compares
# against, and what a release pipeline should attach to the release.
$hash = (Get-FileHash -LiteralPath $OutFile -Algorithm SHA256).Hash
$sidecar = "$OutFile.sha256"
Set-Content -LiteralPath $sidecar -Value "$hash  $(Split-Path $OutFile -Leaf)" -Encoding ASCII

$size = [Math]::Round((Get-Item $OutFile).Length / 1KB, 1)
Write-Host ''
Write-Host "Built $OutFile ($size KB, parses clean)" -ForegroundColor Green
Write-Host "SHA256 $hash" -ForegroundColor DarkGray
Write-Host "       -> $sidecar" -ForegroundColor DarkGray
